[package]
name = "tax_ids"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
roxmltree = "0.19.0"
chrono = "0.4.38"

