[package]
name = "tax_ids"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.4"
reqwest = "0.12.4"
roxmltree = "0.19.0"
chrono = "0.4.38"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
