# Used fields
organisasjonsnummer = "organizationNumber"
navn = "name"
registrertIMvaregisteret = "registeredInVatRegister"
konkurs = "bankruptcy"
underAvvikling = "underLiquidation"
underTvangsavviklingEllerTvangsopplosning = "underForcedLiquidation"
# Other fields
organisasjonsform = "organizationForm"
kode = "code"
beskrivelse = "description"
hjemmeside = "homepage"
registreringsdatoEnhetsregisteret = "registrationDate"
naeringskode1 = "industryCode1"
antallAnsatte = "numberOfEmployees"
harRegistrertAntallAnsatte = "hasRegisteredNumberOfEmployees"
forretningsadresse = "businessAddress"
land = "country"
landkode = "countryCode"
postnummer = "postalCode"
poststed = "city"
adresse = "street"
kommune = "municipality"
kommunenummer = "municipalityCode"
stiftelsesdato = "establishmentDate"
institusjonellSektorkode = "institutionalSectorCode"
registrertIForetaksregisteret = "registeredInBusinessRegister"
registrertIStiftelsesregisteret = "registeredInFoundationRegister"
registrertIFrivillighetsregisteret = "registeredInVoluntaryRegister"
sisteInnsendteAarsregnskap = "lastSubmittedAnnualAccounts"
maalform = "language"
vedtektsdato = "articlesOfAssociationDate"
vedtektsfestetFormaal = "articlesOfAssociationPurpose"
aktivitet = "activity"
slettedato = "deletionDate"
