name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        feature: [eu_vat, gb_vat, ch_vat, no_vat]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.feature }}
      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.feature }}
